### PR TITLE
write_hex_file: new parameter byte_count

### PR DESCRIPTION
**Pull request by erki1993**
can choose hex data field length

### CODE REVIEW

**Comment by bialix** [comment]
You need a check for byte_count value at the beginning of that method, and at least add one more unit test to check desired behaviour. I'd like to have 2 tests: for byte_count = 1, and something between 2 and 15 to check that everything works as expected.

**Comment by erki1993** [comment]
added byte_count check and unitests for 1, 13 and 255 byte counts

**Comment by bialix** [comment]
Thank you @erki1993 - I need to run new tests on different Python versions and then I can merge it.

**Comment by The-42** [comment]
What stops this from being merged? Things seem work as advertised 👍

**Comment by bialix** [comment]
Merged to master with some minor changes. Thank you for patch.

**Pull request closed without merging**
